spring:
  application:
    name: lms-email-impl
  mail:
    host: mail-relay.iu.edu
    port: 587
    username: lmssmtp
    password: ${smtpPassword}
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
lmsemail:
  enabled: false
  signingEnabled: false
  defaultFrom: essnorep@iu.edu
  env: ${app.env}
---

spring:
  profiles: emailEnabled
lmsemail:
  enabled: true

---

spring:
  profiles: emailSigningEnabled
lmsemail:
  signingEnabled: true